/**********************************************************************
* Class Name: DHC_ConstantsUtils
* Author: Accenture
* Date: 12-Jul-2016  
* Description: To store constants of Dynamic Helath Check
***********************************************************************/
public class DHC_ConstantsUtils{
    public final static String COMPANYLOGO= 'Company Logo';
    public final static String DAILYLIMIT= 'Daily Limit';
    public final static String HOURLYLIMIT= 'Hourly Limit';
    public final static String CONCURRENTLIMIT= 'Concurrent Limit';
    public final static String SYSTEMLIMIT= 'System Storage Limit';
    public final static String ENDPOINTURL= 'https://splunk--stg.cs15.my.salesforce.com/services/data/v37.0/limits/';
    public final static String RED= 'Red';
    public final static String YELLOW= 'Yellow';
    public final static String GREEN= 'Green';
    public final static String RUNTIMELIMIT ='RunTime Limit';
    public final static String CLASSSTR = 'Class';
    public final static String LIMITTHRESHOLDOBJ ='Limits_Threshold';
    public final static String DHC_SETUPCUSTOMSETTINGDATA = 'DHC_SetUpCustomSettingData';
    public final static String DHC_RUNTIMEMAXLIMITBATCH =  'DHC_RunTimeMaxLimitBatch';
    public final static String DHC_ORGANIZATIONLIMITMAXLIMITBATCH=  'DHC_OrganizationLimitMaxLimitBatch';
    public final static String DHC_SETTHRESHOLDCONTROLLER=  'DHC_SetThresholdController';
    public final static String DHC_RUNTIMELIMIT= 'RunTime Limit';
    public final static String DHC_AUTHORIZATION= 'Authorization';
    public final static String DHC_BEARER= 'Bearer ';
    public final static String DHC_CONTENTTYPE='Content-Type';
    public final static String DHC_APPLICATIONJSON='application/json';
    public final static String DHC_ACCEPT='accept';
    public final static String DHC_GET='GET';
    public final static String DHC_LIMITQUERY = 'Select id from Limits_Threshold__c limit 1';
    public final static String DHC_APEXUSED ='Apex Used';
    public final static String DHC_ISTEST ='isTest';
      public final static String DHC_DASH= '-';
    public final static String DHC_TYPESTR= 'type';
    public final static String DHC_SOBJECTSTR= 'Sobj';
    public final static String DHC_COMPSTR= 'Comp';
    public final static String PRIORSTR= 'prior';
    public final static String DHC_CRED=  'DHC Credtial';
    public final static String DHC_POST = 'POST';
    
}